# razorops.yaml

version: 2
workflows:
  deploy_to_s3:
    jobs:
      - name: deploy_to_s3
        docker:
          - image: ubuntu:20.04

        steps:
          - checkout

          - run: |
              apt-get update -y
              apt-get install -y awscli

          - run: |
              aws configure set aws_access_key_id ${{ secrets.AKIAUEEQUF2IBS4VSQF2 }}
              aws configure set aws_secret_access_key ${{ secrets.Wt1dRIN1EG3JsT1sCEzBMVZVCgjkhCmobLt3oMtJ }}
              aws configure set default.region us-east-1

          - run: |
              aws s3 sync . s3://${{ secrets.razorops.p-1 }} --delete
